CREATE TYPE IF NOT EXISTS "EventType" AS ENUM ('APPOINTMENT', 'MEETING', 'WEBINAR', 'TRAINING', 'CONSULTATION', 'OTHER');

ALTER TABLE IF EXISTS "events" ADD COLUMN IF NOT EXISTS "event_type" "EventType" NOT NULL DEFAULT 'APPOINTMENT';
ALTER TABLE IF EXISTS "events" ADD COLUMN IF NOT EXISTS "location" TEXT;
ALTER TABLE IF EXISTS "events" ADD COLUMN IF NOT EXISTS "end_time" TIMESTAMPTZ;
ALTER TABLE IF EXISTS "events" ADD COLUMN IF NOT EXISTS "description" TEXT;
