import { library } from '@fortawesome/fontawesome-svg-core'
import { config } from '@fortawesome/fontawesome-svg-core'

import {
    faBell,
    faCalendar,
    faUser,
    faChartLine,
    faCog,
    faEnvelope,
    faClock,
    faCheck,
    faXmark,
    faExclamationTriangle,
    faLock,
    faCreditCard,
    faBolt,
    faShieldHalved,
    faCoins,
    faComment,
    faPhone,
    faRobot,
    faFileAlt,
    faInfoCircle,
    faRocket,
    faMobileAlt,
    faFolderOpen,
    faUsers,
    faBullhorn,
    faSmile,
    faStar,
    faInbox,
    faChartBar,
    faTimes,
    faExclamationCircle,
    faWandMagicSparkles,
    faPalette,
    faBullseye,
    faClipboard,
    faFlagCheckered,
    faMoon,
    faTag,
    faPlay,
    faTooth,
    faScissors,
    faDesktop,
    faGlassCheers,
    faBuilding,
    faLightbulb,
    faSignOutAlt
} from '@fortawesome/free-solid-svg-icons'

import {
    faWhatsapp
} from '@fortawesome/free-brands-svg-icons'

import '@fortawesome/fontawesome-svg-core/styles.css'

config.autoAddCss = false

library.add(
    faBell,
    faCalendar,
    faUser,
    faChartLine,
    faCog,
    faEnvelope,
    faClock,
    faCheck,
    faXmark,
    faExclamationTriangle,
    faLock,
    faCreditCard,
    faBolt,
    faShieldHalved,
    faCoins,
    faComment,
    faPhone,
    faRobot,
    faFileAlt,
    faInfoCircle,
    faRocket,
    faMobileAlt,
    faFolderOpen,
    faUsers,
    faBullhorn,
    faSmile,
    faStar,
    faInbox,
    faChartBar,
    faTimes,
    faExclamationCircle,
    faWandMagicSparkles,
    faPalette,
    faBullseye,
    faClipboard,
    faFlagCheckered,
    faMoon,
    faTag,
    faPlay,
    faTooth,
    faScissors,
    faDesktop,
    faGlassCheers,
    faBuilding,
    faLightbulb,
    faSignOutAlt,
    faWhatsapp
)
